# Generated by Django 6.0.5 on 2026-05-15 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('market', models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('stocks', 'Stocks/Equities'), ('synthetic', 'Synthetic Indices')], max_length=20)),
                ('direction', models.CharField(choices=[('long', 'Long / Buy'), ('short', 'Short / Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven')], max_length=15, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('strategy', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='trade_screenshots/')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
