# Generated by Django 6.0.5 on 2026-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='lot_size',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
